version: '3'
services:
  laravel.test:
    container_name: ms-laravel-app
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    image: sail-8.1/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '88:80'
    environment:
      WWWUSER: '1000'
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel

  meilisearch142:
    image: 'getmeili/meilisearch:v1.4.2'
    ports:
      - '7739:7700'
    volumes:
      - 'meilisearch142:/data.ms'
      - '.:/www'
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
volumes:
  meilisearch142:
    driver: local
